all:
	mkdir -p tmp
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj.dtb sun50i-h5-ytkj.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj000.dtb sun50i-h5-ytkj000.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj001.dtb sun50i-h5-ytkj001.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj002.dtb sun50i-h5-ytkj002.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj003.dtb sun50i-h5-ytkj003.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj004.dtb sun50i-h5-ytkj004.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj005.dtb sun50i-h5-ytkj005.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj006.dtb sun50i-h5-ytkj006.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj007.dtb sun50i-h5-ytkj007.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj008.dtb sun50i-h5-ytkj008.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj009.dtb sun50i-h5-ytkj009.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj010.dtb sun50i-h5-ytkj010.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj011.dtb sun50i-h5-ytkj011.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj012.dtb sun50i-h5-ytkj012.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj013.dtb sun50i-h5-ytkj013.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj014.dtb sun50i-h5-ytkj014.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj015.dtb sun50i-h5-ytkj015.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj016.dtb sun50i-h5-ytkj016.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj017.dtb sun50i-h5-ytkj017.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj018.dtb sun50i-h5-ytkj018.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj019.dtb sun50i-h5-ytkj019.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj020.dtb sun50i-h5-ytkj020.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj021.dtb sun50i-h5-ytkj021.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj022.dtb sun50i-h5-ytkj022.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj023.dtb sun50i-h5-ytkj023.dts
	dtc -I dts -O dtb -o tmp/sun50i-h5-ytkj024.dtb sun50i-h5-ytkj024.dts
clean:
	rm ./tmp -rf
